### ISSUE TITLE
How about this project ?

### ISSUE THREAD

**Issue by PePoDev** [CymaticLabs/Unity3D.Amqp#16]
This project is continue supporting Or deprecated ?

**Comment by klydra** [comment]
I mean, to me it seems like it.
I actually, after many hours of research, got my RabbitMQ Client in Unity working by importing [RawRabbit ](https://www.nuget.org/packages/RawRabbit/) using [nuget for Unity](https://github.com/GlitchEnzo/NuGetForUnity). From there you can either use the official RabbitMQ .NET Client by importing `using RabbitMQ.Client;` [(docs here)](https://www.rabbitmq.com/dotnet-api-guide.html) or use RawRabbit by importing `using RawRabbit;`.

**Comment by PePoDev** [comment]
Thanks a lot

**Comment by YamazakiYasuhiro** [comment]
Great! Thx a lot.
I thought I should repair something at AmqpClient code for Unity has a bit problem of reconnection before I had read these comments.
